branches:
  only:
  - master
  - testing
  - debian-testing

language: cpp

dist: xenial

addons:
  apt:
    update: true

matrix:
  include:
  - name: "SGpp-travis-package"
    addons:
      apt:
        packages:
        - fakeroot
        - scons
        - swig
        - python3-dev
        - python3-numpy
        - python3-jinja2
        - libgomp1
    script:
    - ./tool/travis_scripts/create_deb_install_deb_and_test.sh
