branches:
  only:
  - master
  - testing
  - debian-testing

language: cpp

dist: xenial

addons:
  apt:
    update: true

matrix:
  include:
  - name: "SGpp-travis-package"
    addons:
      apt:
        packages:
        - fakeroot
        - scons
        - swig
        - python3-dev
        - python3-numpy
        - python3-jinja2
        - libgomp1
    script:
    - scons -j 2 SG_ALL=0 SG_BASE=1 SG_PYTHON=1 SG_JAVA=1 RUN_CPP_EXAMPLES=1 RUN_PYTHON_EXAMPLES=1