SG++-Doxygen-Documentation: sgpp::base::sle_solver::IterativeGaussianElimination Class Reference
sgpp::base::sle_solver::IterativeGaussianElimination Class Reference
An incremental linear system solver based on Gaussian elimination.
#include <IterativeGaussianElimination.hpp>
Public Member Functions
IterativeGaussianElimination ()
Default constructor.
bool iterativeSolve (SLE &system, DataVector &b, DataVector &x)
Solves the linear system Ax = b using an incremental LU decomposition.
bool solve (SLE &system, DataVector &b, DataVector &x) const override
This class maintains state for incremental updates, so the const version of solve() is not supported.
~IterativeGaussianElimination () override
Destructor.
Public Member Functions inherited from sgpp::base::sle_solver::SLESolver
SLESolver ()
Constructor.
virtual bool solve (SLE &system, DataMatrix &B, DataMatrix &X) const
Virtual method for solving multiple linear systems with different right-hand sides.
virtual ~SLESolver ()
Destructor.
Static Public Attributes
static constexpr const double DEGENERATION_TOLERANCE = 1e-9
Tolerance to detect near-zero pivots, which could indicate matrix degeneration.
Protected Attributes
DataMatrix A
A copy of the system matrix from the last solve.
DataMatrix LU
The in-place LU decomposition of the matrix A.
std::vector< size_t > pivotCol
Pivot indices for columns (used for full pivoting).
std::vector< size_t > pivotRow
Pivot indices for rows.
Detailed Description
An incremental linear system solver based on Gaussian elimination.
This solver computes a fully-pivoted LU decomposition of the system matrix. For subsequent solves of systems that have been extended with new rows and columns, it efficiently updates the existing decomposition rather than recomputing it from scratch.
Warning
The solver has no way of measuring whether numerical errors accumulate. However, if a zero entry occurs, the solver automatically performs a complete recalculation to ensure stability.
Constructor & Destructor Documentation
IterativeGaussianElimination()
sgpp::base::sle_solver::IterativeGaussianElimination::IterativeGaussianElimination ()
Default constructor.
~IterativeGaussianElimination()
sgpp::base::sle_solver::IterativeGaussianElimination::~IterativeGaussianElimination () override
Destructor.
Member Function Documentation
iterativeSolve()
bool sgpp::base::sle_solver::IterativeGaussianElimination::iterativeSolve (SLE & system, DataVector & b, DataVector & x)
Solves the linear system Ax = b using an incremental LU decomposition.
If the system matrix A has grown since the last call, the solver will update its internal LU decomposition. If the update fails due to numerical instability, a full decomposition is computed.
Parameters
system The linear system to be solved (provides the matrix A).
b The right-hand side vector.
[out] x The solution vector.
Returns
True if the solution was successful, false otherwise (e.g., matrix is singular).
References A, DEGENERATION_TOLERANCE, sgpp::base::SLE::getDimension(), sgpp::base::Printer::getInstance(), sgpp::base::SLE::getMatrixEntry(), sgpp::base::DataMatrix::getNcols(), LU, pivotCol, pivotRow, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), and sgpp::base::DataMatrix::resizeQuadratic().
solve()
bool sgpp::base::sle_solver::IterativeGaussianElimination::solve (SLE & system, DataVector & b, DataVector & x) const inline override virtual
This class maintains state for incremental updates, so the const version of solve() is not supported.
Calling this method will throw a std::runtime_error. Please use iterativeSolve() instead.
Implements sgpp::base::sle_solver::SLESolver.
Member Data Documentation
A
DataMatrix sgpp::base::sle_solver::IterativeGaussianElimination::A protected
A copy of the system matrix from the last solve.
Referenced by iterativeSolve().
DEGENERATION_TOLERANCE
constexpr const double sgpp::base::sle_solver::IterativeGaussianElimination::DEGENERATION_TOLERANCE = 1e-9 static constexpr
Tolerance to detect near-zero pivots, which could indicate matrix degeneration.
Referenced by iterativeSolve().
LU
DataMatrix sgpp::base::sle_solver::IterativeGaussianElimination::LU protected
The in-place LU decomposition of the matrix A.
Referenced by iterativeSolve().
pivotCol
std::vector<size_t> sgpp::base::sle_solver::IterativeGaussianElimination::pivotCol protected
Pivot indices for columns (used for full pivoting).
Referenced by iterativeSolve().
pivotRow
std::vector<size_t> sgpp::base::sle_solver::IterativeGaussianElimination::pivotRow protected
Pivot indices for rows.
Referenced by iterativeSolve().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/sle/solver/IterativeGaussianElimination.hpp
base/src/sgpp/base/tools/sle/solver/IterativeGaussianElimination.cpp