SG++-Doxygen-Documentation: sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak Class Reference
sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak Class Reference
Iterative grid generation based on a modified, fully adaptive Ritter/Novak's refinement criterion.
#include <IterativeGridGeneratorFullAdaptiveRitterNovak.hpp>
Public Member Functions
void activateStoppingCriterion (const std::vector< sgpp::base::DataVector > &validationPoints)
Activates the stopping criterion.
void disableStoppingCriterion ()
Disables the stopping criterion.
bool generate () override
Generates the grid adaptively until the maximum number of points N is reached or a stopping criterion is met.
const base::DataVector & getAlpha () const
const IGGFARNHelper::Hyperparameters & getHyperparameters () const
base::level_t getInitialLevel () const
base::level_t getMaxLevel () const
bool isStoppingCriterionEnabled () const
IterativeGridGeneratorFullAdaptiveRitterNovak (base::ScalarFunction &f, base::Grid &grid, size_t N, const IGGFARNHelper::Hyperparameters &hyperparameters, const std::vector< std::pair< double, double > > &domain, bool refineLeftOrRight=true, const base::level_t initialLevel=DEFAULT_INITIAL_LEVEL, const base::level_t maxLevel=DEFAULT_MAX_LEVEL)
Constructor.
void setHyperparameters (const IGGFARNHelper::Hyperparameters &hyperparameters)
void setInitialLevel (base::level_t initialLevel)
void setMaxLevel (base::level_t maxLevel)
~IterativeGridGeneratorFullAdaptiveRitterNovak () override
Destructor.
Public Member Functions inherited from sgpp::optimization::IterativeGridGenerator
const base::DataVector & getFunctionValues () const
base::Grid & getGrid () const
IterativeGridGenerator (base::ScalarFunction &f, base::Grid &grid, size_t N)
Constructor.
void printIterativeGridGenerator () const
Prints grid points and function values.
virtual ~IterativeGridGenerator ()
Destructor.
Static Public Attributes
static const base::level_t DEFAULT_INITIAL_LEVEL = 3
Default level of the initial regular sparse grid.
static const base::level_t DEFAULT_MAX_LEVEL = 20
Default maximal level of grid points.
Protected Attributes
base::DataVector alpha
Coefficients of the sparse grid surrogate.
std::vector< std::pair< double, double > > domain
Domain bounds for each dimension.
IGGFARNHelper::Hyperparameters hyperparameters
Hyperparameters for the adaptive weight function.
base::level_t initialLevel
Level of the initial regular sparse grid.
base::level_t maxLevel
Maximal level of grid points.
bool refineLeftOrRight
Whether to refine only the left or right child in each dimension.
std::vector< sgpp::base::DataVector > stoppingCriterionValidationPoints
Validation points for the stopping criterion. Empty if disabled.
Protected Attributes inherited from sgpp::optimization::IterativeGridGenerator
base::ScalarFunction & f
objective function
base::DataVector functionValues
vector of function values at the grid points
base::Grid & grid
underlying grid
size_t N
maximal number of grid points
Additional Inherited Members
Protected Member Functions inherited from sgpp::optimization::IterativeGridGenerator
void evalFunction (size_t oldGridSize=0)
Evaluates the objective function at grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] and saves values in functionValues.
void undoRefinement (size_t oldGridSize)
Removes grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] from the grid.
Detailed Description
Iterative grid generation based on a modified, fully adaptive Ritter/Novak's refinement criterion.
This generator uses a combination of weighted criteria to decide which grid point to refine. The criteria include the grid point's level, function value (threshold), gradient, and more. A large number of hyperparameters allow these criteria to be weighted differently.
Warning
This class uses HashRefinementMultiple, so it generates grids that may not meet the "hierarchical ancestors" requirement.
Literature: Julius von Smercek, Bachelor Thesis `‘Critical Event Estimation using Gradient-based Refinement Methods for Adaptive Sparse Grids’', 2025
See also
HashRefinementMultiple
Constructor & Destructor Documentation
IterativeGridGeneratorFullAdaptiveRitterNovak()
sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::IterativeGridGeneratorFullAdaptiveRitterNovak (base::ScalarFunction & f, base::Grid & grid, size_t N, const IGGFARNHelper::Hyperparameters & hyperparameters, const std::vector< std::pair< double, double > > & domain, bool refineLeftOrRight = true, const base::level_t initialLevel = DEFAULT_INITIAL_LEVEL, const base::level_t maxLevel = DEFAULT_MAX_LEVEL)
Constructor.
Do not destruct the grid object before this generator object!
Parameters
f Objective function.
grid Grid object (should be empty).
N Maximal number of grid points.
hyperparameters Hyperparameters for the adaptive weight function.
domain Domain for each dimension
refineLeftOrRight Whether to only refine the left or right child in each dimension, activating the "full adaptive" approach.
initialLevel Level of the initial regular sparse grid.
maxLevel Maximal level permitted for any grid point.
~IterativeGridGeneratorFullAdaptiveRitterNovak()
sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::~IterativeGridGeneratorFullAdaptiveRitterNovak () override
Destructor.
Member Function Documentation
activateStoppingCriterion()
void sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::activateStoppingCriterion (const std::vector< sgpp::base::DataVector > & validationPoints)
Activates the stopping criterion.
The generation will stop if the surrogate model's predictions stabilize between iterations.
Parameters
validationPoints A set of points used to compare surrogate models.
References stoppingCriterionValidationPoints.
disableStoppingCriterion()
void sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::disableStoppingCriterion ()
Disables the stopping criterion.
References stoppingCriterionValidationPoints.
generate()
bool sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::generate () override virtual
Generates the grid adaptively until the maximum number of points N is reached or a stopping criterion is met.
Returns
True on success, false otherwise.
Implements sgpp::optimization::IterativeGridGenerator.
References domain, sgpp::optimization::IterativeGridGenerator::evalFunction(), sgpp::optimization::IterativeGridGenerator::f, sgpp::optimization::IterativeGridGenerator::functionValues, g, sgpp::optimization::IGGFARNHelper::Hyperparameters::getExtendedThreshold(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getGaussianProcess(), sgpp::base::Grid::getGenerator(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getGradient(), sgpp::base::Printer::getInstance(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getLevelDegree(), sgpp::base::ScalarFunction::getNumberOfParameters(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getSecondGradient(), sgpp::base::Grid::getStorage(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getThreshold(), sgpp::optimization::IterativeGridGenerator::grid, hyperparameters, initialLevel, isStoppingCriterionEnabled(), maxLevel, sgpp::optimization::IterativeGridGenerator::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), refineLeftOrRight, sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::setAll(), stoppingCriterionValidationPoints, and sgpp::optimization::IterativeGridGenerator::undoRefinement().
getAlpha()
const base::DataVector & sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::getAlpha () const
Returns
The coefficients (surpluses) of the final sparse grid interpolant.
References alpha.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction().
getHyperparameters()
const IGGFARNHelper::Hyperparameters & sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::getHyperparameters () const
Returns
The currently used hyperparameters.
References hyperparameters.
getInitialLevel()
base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::getInitialLevel () const
Returns
Level of the initial regular sparse grid.
References initialLevel.
getMaxLevel()
base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::getMaxLevel () const
Returns
Maximal permitted level for grid points.
References maxLevel.
isStoppingCriterionEnabled()
bool sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::isStoppingCriterionEnabled () const
Returns
True if the stopping criterion is enabled, false otherwise.
References stoppingCriterionValidationPoints.
Referenced by generate().
setHyperparameters()
void sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::setHyperparameters (const IGGFARNHelper::Hyperparameters & hyperparameters)
Parameters
hyperparameters New hyperparameters for the adaptive weight function.
References hyperparameters.
setInitialLevel()
void sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::setInitialLevel (base::level_t initialLevel)
Parameters
initialLevel New level for the initial regular sparse grid.
References initialLevel.
setMaxLevel()
void sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::setMaxLevel (base::level_t maxLevel)
Parameters
maxLevel New maximal level for grid points.
References maxLevel.
Member Data Documentation
alpha
base::DataVector sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::alpha protected
Coefficients of the sparse grid surrogate.
Referenced by python.learner.Learner.Learner::doLearningIteration(), getAlpha(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Interpolant.Interpolant::learnDataWithTest(), python.uq.dists.SGDEdist.SGDEdist::pdf(), and python.uq.dists.SGDEdist.SGDEdist::toJson().
DEFAULT_INITIAL_LEVEL
const base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::DEFAULT_INITIAL_LEVEL = 3 static
Default level of the initial regular sparse grid.
DEFAULT_MAX_LEVEL
const base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::DEFAULT_MAX_LEVEL = 20 static
Default maximal level of grid points.
domain
std::vector<std::pair<double, double> > sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::domain protected
Domain bounds for each dimension.
Referenced by generate().
hyperparameters
IGGFARNHelper::Hyperparameters sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::hyperparameters protected
Hyperparameters for the adaptive weight function.
Referenced by generate(), getHyperparameters(), and setHyperparameters().
initialLevel
base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::initialLevel protected
Level of the initial regular sparse grid.
Referenced by generate(), getInitialLevel(), and setInitialLevel().
maxLevel
base::level_t sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::maxLevel protected
Maximal level of grid points.
Referenced by generate(), getMaxLevel(), python.uq.operations.forcePositivity.localHierarchicalIntersectionSearch.LocalHierarchicalIntersectionCandidates::getMaxLevelOfChildrenUpToMaxLevel(), python.uq.refinement.AdmissibleSet.AdmissibleSetGenerator::insertPoint(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), and setMaxLevel().
refineLeftOrRight
bool sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::refineLeftOrRight protected
Whether to refine only the left or right child in each dimension.
Referenced by generate().
stoppingCriterionValidationPoints
std::vector<sgpp::base::DataVector> sgpp::optimization::IterativeGridGeneratorFullAdaptiveRitterNovak::stoppingCriterionValidationPoints protected
Validation points for the stopping criterion. Empty if disabled.
Referenced by activateStoppingCriterion(), disableStoppingCriterion(), generate(), and isStoppingCriterionEnabled().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.cpp