SG++-Doxygen-Documentation: sgpp::optimization::IGGFARNHelper::UncertaintyBound Class Reference
sgpp::optimization::IGGFARNHelper::UncertaintyBound Class Reference
A class to represent a value with uncertainty bounds, typically from sampling.
#include <IterativeGridGeneratorFullAdaptiveRitterNovak.hpp>
Public Member Functions
double coV () const
UncertaintyBound div (const UncertaintyBound &other) const
Divides this uncertainty bound by another.
double lower () const
UncertaintyBound ()
Default constructor, initializes to zero.
UncertaintyBound (double lower, double value, double upper, double coV)
Construct from explicit lower, value, upper, and CoV.
UncertaintyBound (size_t samples, size_t N)
Construct from a number of positive samples out of a total number of samples.
double upper () const
double value () const
Detailed Description
A class to represent a value with uncertainty bounds, typically from sampling.
Constructor & Destructor Documentation
UncertaintyBound() [1/3]
sgpp::optimization::IGGFARNHelper::UncertaintyBound::UncertaintyBound (double lower, double value, double upper, double coV) inline
Construct from explicit lower, value, upper, and CoV.
Parameters
lower Lower bound.
value The estimated value.
upper Upper bound.
coV Coefficient of variation.
UncertaintyBound() [2/3]
sgpp::optimization::IGGFARNHelper::UncertaintyBound::UncertaintyBound () inline
Default constructor, initializes to zero.
Referenced by div().
UncertaintyBound() [3/3]
sgpp::optimization::IGGFARNHelper::UncertaintyBound::UncertaintyBound (size_t samples, size_t N) inline
Construct from a number of positive samples out of a total number of samples.
Calculates the value and confidence interval.
Parameters
samples Number of positive samples.
N Total number of samples.
Member Function Documentation
coV()
double sgpp::optimization::IGGFARNHelper::UncertaintyBound::coV () const inline
div()
UncertaintyBound sgpp::optimization::IGGFARNHelper::UncertaintyBound::div (const UncertaintyBound & other) const inline
Divides this uncertainty bound by another.
Used for relative error estimation.
Parameters
other The divisor.
Returns
A new UncertaintyBound representing the quotient.
References lower(), UncertaintyBound(), upper(), and value().
Referenced by sgpp::optimization::IGGFARNHelper::StoppingCriterion::shouldStop().
lower()
double sgpp::optimization::IGGFARNHelper::UncertaintyBound::lower () const inline
Referenced by div(), sgpp::optimization::IGGFARNHelper::operator<<(), and sgpp::optimization::IGGFARNHelper::StoppingCriterion::shouldStop().
upper()
double sgpp::optimization::IGGFARNHelper::UncertaintyBound::upper () const inline
Referenced by div(), sgpp::optimization::IGGFARNHelper::operator<<(), and sgpp::optimization::IGGFARNHelper::StoppingCriterion::shouldStop().
value()
double sgpp::optimization::IGGFARNHelper::UncertaintyBound::value () const inline
Referenced by python.data.DataEntry.DataEntry::__init__(), div(), python.data.DataEntry.DataEntry::getValue(), sgpp::optimization::IGGFARNHelper::operator<<(), and sgpp::optimization::IGGFARNHelper::StoppingCriterion::shouldStop().
The documentation for this class was generated from the following file:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.hpp