SG++-Doxygen-Documentation: sgpp::optimization::IGGFARNHelper::StoppingCriterion Class Reference
sgpp::optimization::IGGFARNHelper::StoppingCriterion Class Reference
Implements a stopping criterion based on the convergence of the surrogate model.
#include <IterativeGridGeneratorFullAdaptiveRitterNovak.hpp>
Public Member Functions
bool shouldStop (base::Grid &grid, const base::DataVector &alpha)
Checks if the grid generation should stop.
StoppingCriterion (const std::vector< sgpp::base::DataVector > &monteCarloPoints)
Constructor.
~StoppingCriterion ()
Destructor.
Protected Member Functions
std::tuple< size_t, UncertaintyBound, UncertaintyBound > measure_error (const std::vector< base::DataVector > &points, std::vector< double > &surrogate_values, std::vector< double > &original_values, const std::function< double(const sgpp::base::DataVector &)> &surrogate_f, const std::function< double(const sgpp::base::DataVector &)> &original_f, const std::function< bool(const UncertaintyBound &, const UncertaintyBound &, size_t)> &early_stop_criterion)
Measures the failure and mismatch probabilities between two functions.
Protected Attributes
std::vector< std::tuple< size_t, std::vector< double >, std::unique_ptr< base::Grid >, base::DataVector > > last_grid_values
const std::vector< sgpp::base::DataVector > & monteCarloPoints
Static Protected Attributes
static const size_t stopping_criterion_count_difference = 50
static constexpr double stopping_criterion_tolerance = 0.025
Detailed Description
Implements a stopping criterion based on the convergence of the surrogate model.
It compares the current grid's surrogate with surrogates from previous iterations. If the relative mismatch probability between them is consistently below a tolerance, it signals to stop.
Constructor & Destructor Documentation
StoppingCriterion()
sgpp::optimization::IGGFARNHelper::StoppingCriterion::StoppingCriterion (const std::vector< sgpp::base::DataVector > & monteCarloPoints) explicit
Constructor.
Parameters
monteCarloPoints Points to use for validation.
~StoppingCriterion()
sgpp::optimization::IGGFARNHelper::StoppingCriterion::~StoppingCriterion ()
Destructor.
Member Function Documentation
measure_error()
std::tuple< size_t, UncertaintyBound, UncertaintyBound > sgpp::optimization::IGGFARNHelper::StoppingCriterion::measure_error (const std::vector< base::DataVector > & points, std::vector< double > & surrogate_values, std::vector< double > & original_values, const std::function< double(const sgpp::base::DataVector &)> & surrogate_f, const std::function< double(const sgpp::base::DataVector &)> & original_f, const std::function< bool(const UncertaintyBound &, const UncertaintyBound &, size_t)> & early_stop_criterion) protected
Measures the failure and mismatch probabilities between two functions.
Parameters
points Points to sample from.
surrogate_values Cache for values of the first function.
original_values Cache for values of the second function.
surrogate_f First function (e.g., current surrogate).
original_f Second function (e.g., previous surrogate).
early_stop_criterion A predicate to decide if sampling can stop early.
Returns
A tuple containing (number of samples used, failure probability, mismatch probability).
Referenced by shouldStop().
shouldStop()
bool sgpp::optimization::IGGFARNHelper::StoppingCriterion::shouldStop (base::Grid & grid, const base::DataVector & alpha)
Checks if the grid generation should stop.
Parameters
grid The current grid.
alpha The current surplus vector.
Returns
True if the stopping criterion is met, false otherwise.
References alpha, sgpp::optimization::IGGFARNHelper::UncertaintyBound::div(), sgpp::base::InterpolantScalarFunction::eval(), sgpp::base::Printer::getInstance(), grid(), last_grid_values, sgpp::optimization::IGGFARNHelper::UncertaintyBound::lower(), measure_error(), monteCarloPoints, sgpp::base::Printer::printStatusUpdate(), stopping_criterion_count_difference, stopping_criterion_tolerance, sgpp::optimization::IGGFARNHelper::UncertaintyBound::upper(), and sgpp::optimization::IGGFARNHelper::UncertaintyBound::value().
Member Data Documentation
last_grid_values
std::vector< std::tuple<size_t, std::vector<double>, std::unique_ptr<base::Grid>, base::DataVector> > sgpp::optimization::IGGFARNHelper::StoppingCriterion::last_grid_values protected
Referenced by shouldStop().
monteCarloPoints
const std::vector<sgpp::base::DataVector>& sgpp::optimization::IGGFARNHelper::StoppingCriterion::monteCarloPoints protected
Referenced by shouldStop().
stopping_criterion_count_difference
const size_t sgpp::optimization::IGGFARNHelper::StoppingCriterion::stopping_criterion_count_difference = 50 static protected
Referenced by shouldStop().
stopping_criterion_tolerance
constexpr double sgpp::optimization::IGGFARNHelper::StoppingCriterion::stopping_criterion_tolerance = 0.025 static constexpr protected
Referenced by shouldStop().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.cpp