SG++-Doxygen-Documentation: sgpp::optimization::IGGFARNHelper::Hyperparameters Class Reference
sgpp::optimization::IGGFARNHelper::Hyperparameters Class Reference
Stores and normalizes the hyperparameters for the refinement criterion.
#include <IterativeGridGeneratorFullAdaptiveRitterNovak.hpp>
Public Member Functions
double getExtendedThreshold () const
double getGaussianProcess () const
double getGradient () const
double getLevelDegree () const
double getSecondGradient () const
double getThreshold () const
Hyperparameters ()
Default constructor, initializes all weights to zero.
Hyperparameters (double levelDegree, double threshold, double extendedThreshold, double gradient, double secondGradient, double gaussianProcess)
Constructor that takes individual weights for each criterion.
Detailed Description
Stores and normalizes the hyperparameters for the refinement criterion.
Constructor & Destructor Documentation
Hyperparameters() [1/2]
sgpp::optimization::IGGFARNHelper::Hyperparameters::Hyperparameters (double levelDegree, double threshold, double extendedThreshold, double gradient, double secondGradient, double gaussianProcess)
Constructor that takes individual weights for each criterion.
The weights are normalized to sum to 1.
Parameters
levelDegree Weight for the level-based criterion.
threshold Weight for the threshold criterion (value at parent).
extendedThreshold Weight for the extended threshold criterion (value at children).
gradient Weight for the gradient-based criterion.
secondGradient Weight for the second-order gradient criterion.
gaussianProcess Weight for the Gaussian Process uncertainty criterion.
Hyperparameters() [2/2]
sgpp::optimization::IGGFARNHelper::Hyperparameters::Hyperparameters ()
Default constructor, initializes all weights to zero.
Member Function Documentation
getExtendedThreshold()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getExtendedThreshold () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
getGaussianProcess()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getGaussianProcess () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
getGradient()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getGradient () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
getLevelDegree()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getLevelDegree () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
getSecondGradient()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getSecondGradient () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
getThreshold()
double sgpp::optimization::IGGFARNHelper::Hyperparameters::getThreshold () const
Referenced by sgpp::optimization::IGGFARNHelper::operator<<().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorFullAdaptiveRitterNovak.cpp