SG++-Doxygen-Documentation: sgpp::optimization::IGGFARNHelper Namespace Reference
sgpp::optimization::IGGFARNHelper Namespace Reference
Helper classes and functions for the IterativeGridGeneratorFullAdaptiveRitterNovak.
Classes
class Hyperparameters
Stores and normalizes the hyperparameters for the refinement criterion.
class StoppingCriterion
Implements a stopping criterion based on the convergence of the surrogate model.
class UncertaintyBound
A class to represent a value with uncertainty bounds, typically from sampling.
Functions
std::ostream & operator<< (std::ostream &os, const Hyperparameters &hyperparameters)
Stream operator for printing hyperparameters.
std::ostream & operator<< (std::ostream &os, const UncertaintyBound &bounds)
Stream operator for printing uncertainty bounds.
Detailed Description
Helper classes and functions for the IterativeGridGeneratorFullAdaptiveRitterNovak.
Function Documentation
operator<<() [1/2]
std::ostream & sgpp::optimization::IGGFARNHelper::operator<< (std::ostream & os, const Hyperparameters & hyperparameters)
Stream operator for printing hyperparameters.
References sgpp::optimization::IGGFARNHelper::Hyperparameters::getExtendedThreshold(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getGaussianProcess(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getGradient(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getLevelDegree(), sgpp::optimization::IGGFARNHelper::Hyperparameters::getSecondGradient(), and sgpp::optimization::IGGFARNHelper::Hyperparameters::getThreshold().
operator<<() [2/2]
std::ostream & sgpp::optimization::IGGFARNHelper::operator<< (std::ostream & os, const UncertaintyBound & bounds)
Stream operator for printing uncertainty bounds.
References sgpp::optimization::IGGFARNHelper::UncertaintyBound::lower(), sgpp::optimization::IGGFARNHelper::UncertaintyBound::upper(), and sgpp::optimization::IGGFARNHelper::UncertaintyBound::value().